dist:
          name: otelcol-custom
          description: Local OpenTelemetry Collector binary
          module: github.com/open-telemetry/opentelemetry-collector
          otelcol_version: 0.40.0
          version: 1.0.0
          output_path: /tmp/dist
        providers:
          - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.45.0/v0.139.0
